version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/netdetect
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - db

  frontend:
    build:
      context: .  # we should move frontend into a nested dir
    command: ./mvnw clean javafx:run  # The command to run your JavaFX frontend
    depends_on:
      - backend  # Ensure frontend starts after backend (optional)

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: netdetect
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
